baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'NaSA helpful notes'

contentDir: "content/en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true

enableRobotsTXT: true
enableGitInfo: true

pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: "tango"

imaging:
  resampleFilter: "CatmullRom"
  quality: 80
  anchor: "smart"

outputs:
  section:
    - "HTML"
    - "print"
    - "RSS"

module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.73.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
